<?php

return [
    'companyName' => 'Shreenathji Home Finance',
    'companyAddress' => 'OFFICE NO 911, R K PRIME, CIRCLE, next to SILVER HEIGHT, Nehru Nagar Co operative Society, Nana Mava, Rajkot, Gujarat 360004',
    'companyPhone' => '+91 99747 89089',
    'companyEmail' => 'info@shf.com',
    'banks' => [
        'HDFC Bank',
        'ICICI Bank',
        'Axis Bank',
        'Kotak Mahindra Bank',
    ],
    'iomCharges' => [
        'thresholdAmount' => 10000000,
        'fixedCharge' => 5500,
        'percentageAbove' => 0.35,
    ],
    'tenures' => [5, 10, 15, 20],
    'documents_en' => [
        'proprietor' => [
            'PAN Card of Proprietor',
            'Aadhaar Card of Proprietor',
            'Business Address Proof',
            'Bank Statement (12 months)',
            'ITR (Last 3 years)',
            'GST Registration Certificate',
            'Shop & Establishment Certificate',
            'Property Documents (if applicable)',
            'Udyam Registration Certificate',
            'Passport Size Photographs',
        ],
        'partnership_llp' => [
            'Partnership Deed / LLP Agreement',
            'PAN Card of Firm / LLP',
            'PAN Card of All Partners',
            'Aadhaar Card of All Partners',
            'Bank Statement (12 months)',
            'ITR of Firm (Last 3 years)',
            'ITR of Partners (Last 3 years)',
            'GST Registration Certificate',
            'Certificate of Incorporation (LLP)',
            'Board Resolution / Authority Letter',
            'Business Address Proof',
            'Passport Size Photographs of All Partners',
        ],
        'pvt_ltd' => [
            'Certificate of Incorporation',
            'Memorandum of Association (MOA)',
            'Articles of Association (AOA)',
            'PAN Card of Company',
            'PAN Card of All Directors',
            'Aadhaar Card of All Directors',
            'Board Resolution for Loan',
            'Bank Statement (12 months)',
            'Audited Financials (Last 3 years)',
            'ITR of Company (Last 3 years)',
            'ITR of Directors (Last 3 years)',
            'GST Registration Certificate',
            'Business Address Proof',
            'Passport Size Photographs of All Directors',
        ],
        'salaried' => [
            'PAN Card',
            'Aadhaar Card',
            'Salary Slips (Last 3 months)',
            'Bank Statement (12 months)',
            'ITR (Last 2 years)',
            'Form 16',
            'Employment / Appointment Letter',
            'ID Card of Company',
            'Property Documents (if applicable)',
            'Passport Size Photographs',
        ],
    ],
    'documents_gu' => [
        'proprietor' => [
            'માલિકનું PAN કાર્ડ',
            'માલિકનું આધાર કાર્ડ',
            'વ્યવસાય સરનામાનો પુરાવો',
            'બેંક સ્ટેટમેન્ટ (૧૨ મહિના)',
            'ITR (છેલ્લા ૩ વર્ષ)',
            'GST નોંધણી પ્રમાણપત્ર',
            'દુકાન અને સ્થાપના પ્રમાણપત્ર',
            'મિલકતના દસ્તાવેજો (જો લાગુ હોય)',
            'ઉદ્યમ નોંધણી પ્રમાણપત્ર',
            'પાસપોર્ટ સાઇઝ ફોટોગ્રાફ',
        ],
        'partnership_llp' => [
            'ભાગીદારી દસ્તાવેજ / LLP કરાર',
            'ફર્મ / LLP નું PAN કાર્ડ',
            'બધા ભાગીદારોનું PAN કાર્ડ',
            'બધા ભાગીદારોનું આધાર કાર્ડ',
            'બેંક સ્ટેટમેન્ટ (૧૨ મહિના)',
            'ફર્મનું ITR (છેલ્લા ૩ વર્ષ)',
            'ભાગીદારોનું ITR (છેલ્લા ૩ વર્ષ)',
            'GST નોંધણી પ્રમાણપત્ર',
            'ઇન્કોર્પોરેશન પ્રમાણપત્ર (LLP)',
            'બોર્ડ ઠરાવ / અધિકૃત પત્ર',
            'વ્યવસાય સરનામાનો પુરાવો',
            'બધા ભાગીદારોના પાસપોર્ટ સાઇઝ ફોટોગ્રાફ',
        ],
        'pvt_ltd' => [
            'ઇન્કોર્પોરેશન પ્રમાણપત્ર',
            'મેમોરેન્ડમ ઑફ એસોસિએશન (MOA)',
            'આર્ટિકલ્સ ઑફ એસોસિએશન (AOA)',
            'કંપનીનું PAN કાર્ડ',
            'બધા ડિરેક્ટરોનું PAN કાર્ડ',
            'બધા ડિરેક્ટરોનું આધાર કાર્ડ',
            'લોન માટે બોર્ડ ઠરાવ',
            'બેંક સ્ટેટમેન્ટ (૧૨ મહિના)',
            'ઑડિટેડ નાણાકીય (છેલ્લા ૩ વર્ષ)',
            'કંપનીનું ITR (છેલ્લા ૩ વર્ષ)',
            'ડિરેક્ટરોનું ITR (છેલ્લા ૩ વર્ષ)',
            'GST નોંધણી પ્રમાણપત્ર',
            'વ્યવસાય સરનામાનો પુરાવો',
            'બધા ડિરેક્ટરોના પાસપોર્ટ સાઇઝ ફોટોગ્રાફ',
        ],
        'salaried' => [
            'PAN કાર્ડ',
            'આધાર કાર્ડ',
            'સેલેરી સ્લિપ (છેલ્લા ૩ મહિના)',
            'બેંક સ્ટેટમેન્ટ (૧૨ મહિના)',
            'ITR (છેલ્લા ૨ વર્ષ)',
            'ફોર્મ ૧૬',
            'નોકરી / નિમણૂક પત્ર',
            'કંપનીનું ID કાર્ડ',
            'મિલકતના દસ્તાવેજો (જો લાગુ હોય)',
            'પાસપોર્ટ સાઇઝ ફોટોગ્રાફ',
        ],
    ],
    'dvrContactTypes' => [
        ['key' => 'existing_customer', 'label_en' => 'Existing Customer', 'label_gu' => 'હાલના ગ્રાહક'],
        ['key' => 'new_customer', 'label_en' => 'New Customer', 'label_gu' => 'નવા ગ્રાહક'],
        ['key' => 'ca', 'label_en' => 'CA', 'label_gu' => 'CA'],
        ['key' => 'builder', 'label_en' => 'Builder/Developer', 'label_gu' => 'બિલ્ડર/ડેવલપર'],
        ['key' => 'dsa', 'label_en' => 'DSA/Connector', 'label_gu' => 'DSA/કનેક્ટર'],
        ['key' => 'other', 'label_en' => 'Other', 'label_gu' => 'અન્ય'],
    ],
    'dvrPurposes' => [
        ['key' => 'new_lead', 'label_en' => 'New Lead', 'label_gu' => 'નવી લીડ'],
        ['key' => 'follow_up', 'label_en' => 'Follow-up', 'label_gu' => 'ફોલો-અપ'],
        ['key' => 'document_collection', 'label_en' => 'Document Collection', 'label_gu' => 'ડોક્યુમેન્ટ કલેક્શન'],
        ['key' => 'quotation_delivery', 'label_en' => 'Quotation Delivery', 'label_gu' => 'ક્વોટેશન ડિલિવરી'],
        ['key' => 'payment', 'label_en' => 'Payment/Disbursement', 'label_gu' => 'ચૂકવણી/વિતરણ'],
        ['key' => 'relationship', 'label_en' => 'Relationship', 'label_gu' => 'સંબંધ'],
        ['key' => 'other', 'label_en' => 'Other', 'label_gu' => 'અન્ય'],
    ],
    'quotationReferralTypes' => [
        ['key' => 'existing_customer', 'label_en' => 'Existing Customer', 'label_gu' => 'હાલના ગ્રાહક'],
        ['key' => 'walk_in', 'label_en' => 'Walk-in', 'label_gu' => 'વોક-ઇન'],
        ['key' => 'dsa', 'label_en' => 'DSA/Connector', 'label_gu' => 'DSA/કનેક્ટર'],
        ['key' => 'builder', 'label_en' => 'Builder/Developer', 'label_gu' => 'બિલ્ડર/ડેવલપર'],
        ['key' => 'ca', 'label_en' => 'CA', 'label_gu' => 'CA'],
        ['key' => 'staff', 'label_en' => 'Staff Reference', 'label_gu' => 'સ્ટાફ સંદર્ભ'],
        ['key' => 'other', 'label_en' => 'Other', 'label_gu' => 'અન્ય'],
    ],
    'quotationHoldReasons' => [
        // Documents
        ['key' => 'awaiting_kyc_docs', 'label_en' => 'Awaiting KYC / Income Documents', 'label_gu' => 'KYC / આવક દસ્તાવેજોની રાહ', 'group' => 'Documents'],
        ['key' => 'awaiting_property_docs', 'label_en' => 'Awaiting Property Documents (NOC, chain, title)', 'label_gu' => 'મિલકત દસ્તાવેજોની રાહ (NOC, ચેઇન, ટાઇટલ)', 'group' => 'Documents'],
        ['key' => 'builder_noc_pending', 'label_en' => 'Builder NOC Pending', 'label_gu' => 'બિલ્ડર NOC બાકી', 'group' => 'Documents'],
        ['key' => 'society_noc_pending', 'label_en' => 'Society NOC / Share Certificate Pending', 'label_gu' => 'સોસાયટી NOC / શેર પ્રમાણપત્ર બાકી', 'group' => 'Documents'],
        ['key' => 'property_legal_opinion_pending', 'label_en' => 'Property Legal Opinion Pending', 'label_gu' => 'મિલકત કાનૂની અભિપ્રાય બાકી', 'group' => 'Documents'],
        ['key' => 'property_valuation_pending', 'label_en' => 'Property Valuation Pending', 'label_gu' => 'મિલકત મૂલ્યાંકન બાકી', 'group' => 'Documents'],

        // Rate / Pricing
        ['key' => 'rate_too_high', 'label_en' => 'Rates Too High — Waiting to Negotiate', 'label_gu' => 'દરો વધુ છે — વાટાઘાટની રાહ', 'group' => 'Rate / Pricing'],
        ['key' => 'awaiting_rate_cut', 'label_en' => 'Awaiting Repo Rate Cut / RBI Policy', 'label_gu' => 'રેપો રેટ ઘટાડો / RBI નીતિની રાહ', 'group' => 'Rate / Pricing'],
        ['key' => 'pf_waiver_pending', 'label_en' => 'Processing Fee Waiver Under Discussion', 'label_gu' => 'પ્રોસેસિંગ ફી છૂટની ચર્ચા ચાલુ', 'group' => 'Rate / Pricing'],
        ['key' => 'rate_negotiation', 'label_en' => 'Rate Negotiation with Bank', 'label_gu' => 'બેંક સાથે દરની વાટાઘાટ', 'group' => 'Rate / Pricing'],
        ['key' => 'fixed_vs_floating_decision', 'label_en' => 'Fixed vs Floating Decision Pending', 'label_gu' => 'ફિક્સ્ડ વિ. ફ્લોટિંગ નિર્ણય બાકી', 'group' => 'Rate / Pricing'],
        ['key' => 'special_scheme_awaited', 'label_en' => 'Awaiting Special Scheme (PMAY / festive offer)', 'label_gu' => 'ખાસ યોજનાની રાહ (PMAY / તહેવાર ઓફર)', 'group' => 'Rate / Pricing'],

        // Amount / Tenure / Eligibility
        ['key' => 'amount_revision_pending', 'label_en' => 'Loan Amount Being Revised', 'label_gu' => 'લોન રકમમાં ફેરફાર ચાલુ', 'group' => 'Amount / Tenure'],
        ['key' => 'tenure_not_suitable', 'label_en' => 'Desired Tenure Not Available', 'label_gu' => 'ઇચ્છિત અવધિ ઉપલબ્ધ નથી', 'group' => 'Amount / Tenure'],
        ['key' => 'ltv_shortfall', 'label_en' => 'Bank LTV Too Low — Arranging Own Contribution', 'label_gu' => 'બેંક LTV ઓછો — પોતાનો હિસ્સો ગોઠવી રહ્યા છે', 'group' => 'Amount / Tenure'],

        // Property
        ['key' => 'property_not_finalized', 'label_en' => 'Property Not Yet Finalized', 'label_gu' => 'મિલકત હજુ નક્કી નથી', 'group' => 'Property'],
        ['key' => 'under_construction_timing', 'label_en' => 'Property Under Construction — Disbursement Timing', 'label_gu' => 'મિલકત બાંધકામ હેઠળ — વિતરણ સમય', 'group' => 'Property'],
        ['key' => 'property_issue', 'label_en' => 'Property Issue (other)', 'label_gu' => 'મિલકત સંબંધી સમસ્યા (અન્ય)', 'group' => 'Property'],

        // Customer
        ['key' => 'customer_reviewing', 'label_en' => 'Customer Reviewing Options', 'label_gu' => 'ગ્રાહક વિકલ્પોની સમીક્ષા કરે છે', 'group' => 'Customer'],
        ['key' => 'customer_undecided', 'label_en' => 'Customer Undecided', 'label_gu' => 'ગ્રાહક અનિર્ણિત', 'group' => 'Customer'],
        ['key' => 'customer_unavailable', 'label_en' => 'Customer Traveling / Unreachable', 'label_gu' => 'ગ્રાહક મુસાફરી / સંપર્ક બહાર', 'group' => 'Customer'],
        ['key' => 'co_applicant_pending', 'label_en' => 'Co-applicant Discussion / Documents', 'label_gu' => 'સહ-અરજદારની ચર્ચા / દસ્તાવેજો', 'group' => 'Customer'],
        ['key' => 'income_update_expected', 'label_en' => 'Waiting for ITR / Salary Update', 'label_gu' => 'ITR / પગાર અપડેટની રાહ', 'group' => 'Customer'],
        ['key' => 'credit_score_improvement', 'label_en' => 'CIBIL Improvement in Progress', 'label_gu' => 'CIBIL સુધારણા ચાલુ', 'group' => 'Customer'],
        ['key' => 'probation_notice_period', 'label_en' => 'Customer on Probation / Notice Period', 'label_gu' => 'ગ્રાહક પ્રોબેશન / નોટિસ પીરિયડમાં', 'group' => 'Customer'],
        ['key' => 'job_change_underway', 'label_en' => 'Job Change in Progress', 'label_gu' => 'નોકરી બદલી ચાલુ', 'group' => 'Customer'],
        ['key' => 'muhurat_timing', 'label_en' => 'Waiting for Auspicious Date (Muhurat)', 'label_gu' => 'મુહૂર્ત / શુભ મુહૂર્તની રાહ', 'group' => 'Customer'],

        // Product / Scheme
        ['key' => 'exploring_bt_topup', 'label_en' => 'Exploring Balance Transfer / Top-up', 'label_gu' => 'બેલેન્સ ટ્રાન્સફર / ટોપ-અપ વિચારી રહ્યા છે', 'group' => 'Product / Scheme'],
        ['key' => 'composite_loan_pending', 'label_en' => 'Composite (Plot + Construction) Structuring', 'label_gu' => 'કમ્પોઝિટ (પ્લોટ + બાંધકામ) રચના', 'group' => 'Product / Scheme'],
        ['key' => 'construction_milestone_wait', 'label_en' => 'Construction Milestone Disbursement Timing', 'label_gu' => 'બાંધકામ માઇલસ્ટોન વિતરણ સમય', 'group' => 'Product / Scheme'],

        // Bank / Policy
        ['key' => 'bank_policy_wait', 'label_en' => 'Awaiting Bank Underwriting / Policy Clarity', 'label_gu' => 'બેંક અન્ડરરાઇટિંગ / નીતિ સ્પષ્ટતાની રાહ', 'group' => 'Bank / Policy'],

        // Other
        ['key' => 'other', 'label_en' => 'Other', 'label_gu' => 'અન્ય', 'group' => 'Other'],
    ],
    'quotationCancelReasons' => [
        // Channel attrition
        ['key' => 'went_direct_to_bank', 'label_en' => 'Customer Went Direct to Bank', 'label_gu' => 'ગ્રાહક સીધા બેંક પાસે ગયા', 'group' => 'Channel Attrition'],
        ['key' => 'went_with_other_dsa', 'label_en' => 'Went Through Another DSA / Connector', 'label_gu' => 'અન્ય DSA / કનેક્ટર દ્વારા ગયા', 'group' => 'Channel Attrition'],
        ['key' => 'competitor_bank', 'label_en' => 'Chose a Bank We Do Not Facilitate', 'label_gu' => 'અમે જે બેંક સાથે કામ કરતા નથી તે પસંદ કરી', 'group' => 'Channel Attrition'],
        ['key' => 'went_with_other_bank', 'label_en' => 'Went With Other Bank', 'label_gu' => 'અન્ય બેંક પસંદ કરી', 'group' => 'Channel Attrition'],
        ['key' => 'customer_declined', 'label_en' => 'Customer Declined', 'label_gu' => 'ગ્રાહકે નકાર્યું', 'group' => 'Channel Attrition'],
        ['key' => 'employer_tie_up', 'label_en' => 'Employer Tie-up With Another Bank', 'label_gu' => 'એમ્પ્લોયરનું અન્ય બેંક સાથે ટાઇ-અપ', 'group' => 'Channel Attrition'],

        // Rate / Pricing
        ['key' => 'rate_better_elsewhere', 'label_en' => 'Better Rate Offered Elsewhere', 'label_gu' => 'અન્યત્ર વધુ સારો દર મળ્યો', 'group' => 'Rate / Pricing'],
        ['key' => 'charges_too_high', 'label_en' => 'Total Charges Too High', 'label_gu' => 'કુલ ચાર્જીસ વધુ છે', 'group' => 'Rate / Pricing'],
        ['key' => 'amount_not_sanctioned', 'label_en' => 'Required Amount Not Sanctionable', 'label_gu' => 'જરૂરી રકમ મંજૂર થઈ શકે તેમ નથી', 'group' => 'Rate / Pricing'],

        // Eligibility / Compliance
        ['key' => 'not_eligible', 'label_en' => 'Not Eligible', 'label_gu' => 'યોગ્ય નથી', 'group' => 'Eligibility / Compliance'],
        ['key' => 'cibil_too_low', 'label_en' => 'CIBIL Score Below Threshold', 'label_gu' => 'CIBIL સ્કોર મર્યાદા થી ઓછો', 'group' => 'Eligibility / Compliance'],
        ['key' => 'income_insufficient', 'label_en' => 'Income Insufficient for Any Bank', 'label_gu' => 'કોઈપણ બેંક માટે આવક પૂરતી નથી', 'group' => 'Eligibility / Compliance'],
        ['key' => 'tax_compliance_issue', 'label_en' => 'ITR / GST Compliance Issue', 'label_gu' => 'ITR / GST અનુપાલન સમસ્યા', 'group' => 'Eligibility / Compliance'],
        ['key' => 'docs_not_furnished', 'label_en' => 'Customer Could Not Furnish Documents', 'label_gu' => 'ગ્રાહક દસ્તાવેજો આપી શક્યા નથી', 'group' => 'Eligibility / Compliance'],

        // Property
        ['key' => 'property_deal_cancelled', 'label_en' => 'Property Deal Fell Through', 'label_gu' => 'મિલકતનો સોદો ભાંગી ગયો', 'group' => 'Property'],
        ['key' => 'property_rejected', 'label_en' => 'Property Rejected (Legal / Technical)', 'label_gu' => 'મિલકત નામંજૂર (કાનૂની / ટેકનિકલ)', 'group' => 'Property'],
        ['key' => 'property_blacklisted', 'label_en' => 'Property / Builder Blacklisted by Banks', 'label_gu' => 'મિલકત / બિલ્ડર બેંકો દ્વારા બ્લેકલિસ્ટેડ', 'group' => 'Property'],
        ['key' => 'title_dispute', 'label_en' => 'Property Title Disputed / Ambiguous', 'label_gu' => 'મિલકત ટાઇટલ વિવાદિત / અસ્પષ્ટ', 'group' => 'Property'],

        // Customer
        ['key' => 'self_funded', 'label_en' => 'Customer Self-Funded', 'label_gu' => 'ગ્રાહકે પોતાના ભંડોળથી ચૂકવ્યું', 'group' => 'Customer'],
        ['key' => 'co_applicant_backed_out', 'label_en' => 'Co-applicant Backed Out', 'label_gu' => 'સહ-અરજદાર પાછા હટ્યા', 'group' => 'Customer'],
        ['key' => 'purchase_postponed', 'label_en' => 'Purchase Postponed Indefinitely', 'label_gu' => 'ખરીદી અનિશ્ચિત સમય માટે મોકૂફ', 'group' => 'Customer'],
        ['key' => 'customer_unresponsive', 'label_en' => 'Customer Unresponsive (30+ days)', 'label_gu' => 'ગ્રાહક અપ્રતિભાવી (30+ દિવસ)', 'group' => 'Customer'],
        ['key' => 'not_serious_lead', 'label_en' => 'Non-serious Enquiry', 'label_gu' => 'ગંભીર પૂછપરછ નથી', 'group' => 'Customer'],
        ['key' => 'medical_emergency', 'label_en' => 'Medical / Family Emergency', 'label_gu' => 'તબીબી / કુટુંબ કટોકટી', 'group' => 'Customer'],

        // Product Mismatch
        ['key' => 'wrong_loan_type', 'label_en' => 'Customer Needed LAP / OD / Different Product', 'label_gu' => 'ગ્રાહકને LAP / OD / અન્ય ઉત્પાદન જોઈતું હતું', 'group' => 'Product Mismatch'],
        ['key' => 'wrong_product_type', 'label_en' => 'Wrong Customer Type / Product — Replaced', 'label_gu' => 'ખોટો ગ્રાહક પ્રકાર / ઉત્પાદન — બદલ્યું', 'group' => 'Product Mismatch'],
        ['key' => 'duplicate', 'label_en' => 'Duplicate Quotation', 'label_gu' => 'ડુપ્લિકેટ ક્વોટેશન', 'group' => 'Product Mismatch'],

        // Other
        ['key' => 'other', 'label_en' => 'Other', 'label_gu' => 'અન્ય', 'group' => 'Other'],
    ],
    'gstPercent' => 18,
    'ourServices' => "Home Loan, Mortgage Loan, Commercial Loan, Industrial Loan,\nLand Loan, Over Draft(OD)",
];
